version: "3"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - net
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: diegofarend/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: 'node index.js'
    networks:
      - net
    ports:
      - "4000:3000"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=teste
    networks:
      - net

networks:
  net:
    driver: bridge
