FROM nginx:1.15.0-alpine

# Deleta o arquivo de configuração padrão do nginx (default.conf) e copia o arquivo personalizado (nginx.conf) para pasta padrão do nginx.
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
